const items =[
    {id:'1',
    name:"Torta de Chocolate",
    description:"Deliciosa torta de chocolate!",
    stock:'3',
    price:'300',
    imgurl:'https://www.hogarmania.com/archivos/201903/postres-chocolate-1280x720x80xX.jpg'},
    {id:'2',
    name:"Cheescake",
    description:"Cheescake",
    stock:'2',
    price:'500',
    imgurl:'https://cdn2.cocinadelirante.com/sites/default/files/styles/gallerie/public/images/2019/06/postres-leche-condensada-y-cafe.jpg'},
    {id:'3',
    name:"Alfajores",
    description:"Alfajores",
    stock:'20',
    price:'900',
    imgurl:'https://ideasparaviajar.com/wp-content/uploads/2020/09/postres-tipicos-de-francia.jpg'},
    {id:'4',
    name:"Tiramisu",
    description:"Tiramisu",
    stock:'1',
    price:'700',
    imgurl:'https://www.clara.es/medio/2019/09/27/postres-con-cafe-tiramisu_ddfb1110_1400x933.jpg'},
]
export default items;    